version: '3.8'

networks:
  app-network:
    external: true
    name: personal-chat-project_app-network

services:
  ai:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/ai
    command: sleep infinity
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development
      - DATABASE_URL=mongodb://db:27017/personal_chat 